### ISSUE TITLE
Tomcat 8にすると動かない？

### ISSUE THREAD

**Issue by yuu-nkjm** [MAGCruise/MAGCruiseBroker#11]
```
java.lang.NullPointerException
	java.io.File.<init>(File.java:277)
	jp.go.nict.langrid.commons.ws.io.ServiceContextFileResolver.resolve(ServiceContextFileResolver.java:40)
	jp.go.nict.langrid.servicecontainer.handler.ServiceLoader.<init>(ServiceLoader.java:61)
	jp.go.nict.langrid.servicecontainer.handler.jsonrpc.servlet.JsonRpcServlet.doGet(JsonRpcServlet.java:194)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:622)
	jp.go.nict.langrid.servicecontainer.handler.jsonrpc.servlet.JsonRpcServlet.service(JsonRpcServlet.java:167)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
```

**Comment by takawitter** [comment]
サービスグリッドライブラリの問題かもしれないですね。

ところで、MAGCruiseの開発環境を再度構築したいんですが、どの
プロジェクトをcloneすればよいでしょう？

**Comment by yuu-nkjm** [comment]
memo
いい加減なissueですみません．

MAGCruiseBrokerをcloneして，submodule updateをかければOKのはずです．

MAGCruiseBrokerはEclipseプロジェクトになっているのでインポートして下さい．

あとは，MAGCruiseBroker\WebContent\WEB-INF以下の
MAGCruiseLibraries
MAGCruiseCore
MAGCruiseScenario
をEclipse上でインポートして下さい．

MAGCruiseBroker\etc\tomcat\Catalina\localhost\magcruise.xml
がTomcatに読み込ませる設定になります．

;; となっているはずですが，submoduleの設定がおかしいようです．
;; 手動で入れて頂いても動くとは思いますが，後ほど，submoduleの設定をこちらで修正します．

**Comment by yuu-nkjm** [comment]
上記の手順で，MAGCruiseBrokerが，Tomcat 7だと動き，Tomcat 8だと動かないことを確認しました．
他のサービスグリッドライブラリを利用したお手製JSON-RPCサービスも，Tomcat 8だと動いていないようです．

また何か分かりましたら，ここに追記します．

;; 今日は通常の月曜日日程で講義でした…

**Comment by takawitter** [comment]
JSON-RPCサービス、サービスリストすら出ませんね・・
とりあえずライブラリを最新のものに置き換えて試してみます。

;; 講義お疲れ様です。関西は台風で金曜が潰れて土曜に講義して、
;; 休みが1日だけになった大学がおおいらしいです。

**Comment by yuu-nkjm** [comment]
こちらでも，サービスのリストすら取れてないですね…．

MAGCruiseLibrariesには，
http://search.maven.org/#search%7Cga%7C1%7Cnet.servicegrid
の最新版，1.0.7を入れています．

ソースを追っかけようとしましたが，難しそうですね．

■正常時(Tomcat 7)
http://gyazo.com/dd1cc81302395b790343108926eb19af

■異常時(Tomcat 8)
http://gyazo.com/dae80458ed4159a0deeee591d0a0b5c8

となってて，ServiceContextFileResolverのresolveをおっかければ良さそうだから…

**Comment by yuu-nkjm** [comment]
ServletConfigServiceContextの以下のメソッド呼び出しが，

http://gyazo.com/e098a48c9c2d70bde5840e67d5d41edb

```java
	@Override
	public String getRealPath(String path) {
		return servletContext.getRealPath(path);
	}
```

Tomcat 7だと値(E:\workspace\.metadata\.plugins\org.eclipse.wst.server.core\tmp0\wtpwebapps\MAGCruiseBroker\WEB-INF\services)がちゃんと返ってくるのに，Tomcat 8だとnullになってますね．

servletContext.getRealPath(path)って，Tomcatが用意しているメソッドですよね．
ちょろっとググると，このメソッド，何か変更があったようですね．

http://stackoverflow.com/questions/29728092/servletcontext-getrealpath-returns-different-results-tomcat7-tomcat8-bug

今日はここまで！ぱたり…

**Comment by takawitter** [comment]
調査ありがとうございます！
ちょうどこちらでも上記調査していて、jp.go.nict.langrid.commonsに場当たり的に修正入れて動作確認しました(後でgetRealPathの仕様ちゃんと調べてからもいっかい修正見直す予定)。

https://github.com/openlangrid/langrid/commit/63370d97c722925749aeb60a9f7aa2f142661d0b

ちょっとSubmoduleの更新がうまく行ってるか自信ないですが、試していただければ。

**Comment by yuu-nkjm** [comment]
https://github.com/openlangrid/langrid/issues/26#event-360115710

修正ありがとうございます．
サービス表示の部分はうまくいきました！

Brokerを動作させる時，ServletServiceContextのgetRealPath呼び出しでも同様のエラーが出ました．
他にServletConfigServiceContext(ServiceContextWrapperも？)も影響があるのではないでしょうか．

他にもjavax.servlet.ServletContext.getRealPathを呼び出している箇所があるなら，
チェックした方が良いかもしれません．

;; javax.servlet.ServletContextをjp.go.nict.langrid.commons.ws.ServiceContextでラップする
;; ように設計されているならば，大丈夫そうですが…．

ご確認をお願い致します！

**Comment by takawitter** [comment]
これ仕様でちゃんと決まってない状態みたいですね。ややこしい。ServletServiceContextとServletConfigServiceContextで対処する予定です。ちょっと今出先なので今週目処くらいで。。
2015/07/21 午後0:35 "Yuu NAKAJIMA" <notifications@github.com>:

**Comment by yuu-nkjm** [comment]
ありがとうございます！お時間のあるときにお願いします．

W大のオープンキャンパス？で使ったのですが，その環境はTomcat 7のままだったので，
事なきを得ました．OSのアップデートは，何かと手間がかかりますねぇ…

**Comment by takawitter** [comment]
最新にしましたー。
ちょっと影響範囲でかそうなので、Tomcat8はまだ怖いですね。
とりあえずいつでもTomcat7に戻れるようにしつつ、試していこうかと思ってます。

**Comment by yuu-nkjm** [comment]
Javaアプリケーションサーバのシェアの動向もありますし，どのタイミングでどの環境に移るか難しいですね．
servicegridはしばらくはtomcat 7で行きそうですか？もうそろそろ，自動インストールだとTomcat8が入って
しまう環境が増えそうですね．

**Comment by takawitter** [comment]
正直Tomcat8のメリットがよくわかってないので、運用は当分7のまま行って、開発環境はそろそろ8も試していこうかなってくらいに考えてます。

**Comment by yuu-nkjm** [comment]
Tomcat 8でも問題なし！

**Comment by takawitter** [comment]
よかった！

**Comment by yuu-nkjm** [comment]
いつもありがとうございます！今後のことを考えると，Broker に登録されたイベントを拾うところで，ポーリングしまくってるところを何とかしたいんですよねー．
