### ISSUE TITLE
非効率なイベントポーリングの代替案を検討する

### ISSUE THREAD

**Issue by takawitter** [MAGCruise/MAGCruiseBroker#12]
https://github.com/MAGCruise/MAGCruiseBroker/issues/11#issuecomment-166630631 から派生．

@yuu-nkjm 具体的にはどこでしたっけ？
ブラウザからだったかSchemeからだったか，記憶が定かで無いです・・

**Comment by yuu-nkjm** [comment]
https://github.com/MAGCruise/MAGCruiseBroker/blob/master/WebContent%2Fjs%2Fgame-session-controller.js#L56 あたりです．

現在は，jsがWebUIにポーリングをかけていますが，ここで効率の良いイベント通知が実装できるなら，jsからBrokerに問合せをかけるようにしたいと思っています．

**Comment by takawitter** [comment]
なるほど．考えられる案としては，
1. pollingする接続を1本にまとめる．
2. WebSocketでサーバからプッシュ．
くらいですかね．

**Comment by yuu-nkjm** [comment]
2番の線で実装をお願いします！(w

**Comment by yuu-nkjm** [comment]
冗談はさておき，例の多言語チャット案件のためにもWebSocketを触っておこうと思うので，分からないことがあったら質問させて下さいm(_ _)m

**Comment by yuu-nkjm** [comment]
@takawitter  さんの直感で教えて欲しいのですが， jp.go.nict.langrid.servicecontainer.service.AbstractService を継承したクラスをいじることで，WebSocketやロングポーリングに対応することって可能ですか？

https://github.com/MAGCruise/MAGCruiseBroker/blob/master/src/org/magcruise/broker/RequestToUIRelayController.java#L52

servicecontainer.* レベルでないと対応できないとすると厳しいなと．

**Comment by takawitter** [comment]
servicecontainer.*レベルでないと対応できませんが，RaSC(https://alaginrc.nict.go.jp/rasc/javadoc/jp/go/nict/ial/websocket/package-use.html )で実装してました．詳細ちょっと見てみます．

**Comment by yuu-nkjm** [comment]
ありがとうございます！

**Comment by takawitter** [comment]
これWebsocketの上でRPCするやつなので，依然としてpollingはする必要がありますね．
ただWebsocket張りっぱなしなのでオーバーヘッドは少ないですけど．

**Comment by takawitter** [comment]
https://github.com/MAGCruise/MAGCruiseBroker/tree/enh-websocket
こっちの方に，イベント取得をWebSocket化したものをcommit/pushしました！
http://localhost:8080/MAGCruiseBroker/index_ws.htmlにアクセスして，
最初のスクリプトのクラスのロード部分を
```scheme
     (def:loader "org.magcruise.gaming.tutorial.trans.resource.ResourceLoader"
```
こうして("scenario"を除去)，Joinの次に進むところまでは動作確認できてます．
ただし，その先は
```
2016-02-09 16:36:40.129 ERROR [pool-8-thread-3] org.magcruise.gaming.model.sys.ResourceLoader.getResource(ResourceLoader.java:44) langrid-conf.json is not found at org.magcruise.gaming.tutorial.trans.resource.
```
こんなエラーが出て先に進みません．
たぶんシナリオ側のエラーだと思います(ws版じゃなくても出るので)

意外とサクッとWS化できました :)

**Comment by yuu-nkjm** [comment]
おぉ，これは嬉しい！

パスワードが書き込まれているlangrid-conf.jsonがレポジトリに入っていないだけなので，
Joinの次にまで進んだなら大丈夫です！

ちらっと差分を見ましたが，JavaとしてはWSManager.javaを追加しただけなのですね．

**Comment by yuu-nkjm** [comment]
これぐらいならすぐ分かるかも…
と思ったけど，分かりませんでしたw

onOpenの時にThread作るのはよいとして，workersに登録されたThreadはどう利用されるのだ…？
春休みの宿題にしたいと思います．

**Comment by yuu-nkjm** [comment]
ちなみに，
```
(def:loader "org.magcruise.gaming.tutorial.trans.resource.ResourceLoader"
```
を
```
(def:loader "org.magcruise.gaming.tutorial.ele.resource.ResourceLoader"
```
や
```
(def:loader  "org.magcruise.gaming.tutorial.croquette.resource.ResourceLoader"
```
に置き換えると，動くはずです．お時間のあるときに，試して頂ければと…

**Comment by takawitter** [comment]
了解ありがとうございます．

onOpen時に作られたスレッドですが，基本イベントキューから読みだしてクライアントに
送るだけで，他の処理からは利用されません．
切断時にinterruptされるだけ．

ブラウザからのイベント送信や，stdout/stderrはまだ従来の接続のままです．

**Comment by yuu-nkjm** [comment]
> onOpen時に作られたスレッドですが，基本イベントキューから読みだしてクライアントに
> 送るだけで，他の処理からは利用されません．切断時にinterruptされるだけ．

寝かしつけ時に気付きました．WebSocketだし，接続にぎりっぱなしになっているのかな，
とか思いましたが，このworkerの再利用とかは関係なかったですね．

- WebUI(php)は，どのリクエストを描画したかといった情報をDBにためているので，
ブラウザを再起動しても，もとの画面に戻れる．
- Broker付属のUI(js)は，どのリクエストを描画したかといった情報は永続的には保存していないので，
ブラウザを再起動すると，もとの画面に戻れない．しかも，イベントキューは，読み出したらその情報をすててしまう．

となっているので，イベントキューを改良しようと思っています．
徐々にPHP製WebUIを捨てるぞー

**Comment by takawitter** [comment]
まぁデバッグ用で複数のユーザへのアクションが全部表示されますしね．
描画情報の記憶は結構めんどくさそうですが，できるとPHPUI排除に大きく近づきますね．

**Comment by yuu-nkjm** [comment]
何も考えずにやるなら，PHP WebUIと一緒のタイミングで，描画情報(というか，どこまで入力したか
情報)をメモリないしDBに保存すれば良さそうです．描画機能は，PHPからJSに移したので，
割とすんなりと移行できるはず．

JSが大きくなってきているので，一工夫したいと思っているのですが，あまり手をかけたくないところ
でもあります．

**Comment by yuu-nkjm** [comment]
WebSocket化に成功しました！ パフォーマンス測定が難しいのですが，ブラウザでタブを開きまくったところ，速くなっていそうです．

WebUIの機能は，ゲームの起動，ユーザ管理，プレーヤ画面への誘導ぐらいになりました．Core+Broker+JSで，ゲームの機能は満たされていて，WebUIはそれらを組み合わせるためのものになりました．

どんどん薄くして，最後はServletに置き換えようかと思っています．ありがとうございました！

**Comment by takawitter** [comment]
素晴らしい！
