### ISSUE TITLE
JsonRpcServletのエラーメッセージの抑制

### ISSUE THREAD

**Issue by yuu-nkjm** [MAGCruise/MAGCruiseBroker#15]
@takawitter さん，

jp.go.nict.langrid.servicecontainer.handler.jsonrpc.servlet.JsonRpcServletの189行目あたりの
```java
			if(dupIn != null && dupIn.size() > 0){
				Logger.getAnonymousLogger().info(String.format(
						"requestInput: %s", new String(dupIn.toByteArray(), "UTF-8")
						));
			}
```
を抑制したい，もしくはlog4j2に流し込みたいのですが，何か良い方法はあるでしょうか？

また，jp.go.nict.langrid.servicecontainer.handler.jsonrpc.servlet.JsonRpcServlet のソースコードってどのレポジトリのものを参照するのが良いでしょうか？

**Comment by takawitter** [comment]
dumpRequestsオプションをfalseにすれば，抑制できるはずです．
log4j2はちと難しいかも・・java.util.logging.Handlerを継承したクラス作ってlogging.propertiesで指定すればできるかもしれませんが．

**Comment by yuu-nkjm** [comment]
> dumpRequestsオプションをfalseにすれば，抑制できるはずです．

おっと，そのフラグを見落としていました…m(_ _)m

> log4j2はちと難しいかも・・java.util.logging.Handlerを継承したクラス作ってlogging.propertiesで指定すればできるかもしれませんが．

止めておきます…w
